# Generated by Django 5.2.6 on 2025-09-18 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuadraticEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(help_text='Coefficient of x²')),
                ('b', models.FloatField(help_text='Coefficient of x')),
                ('c', models.FloatField(help_text='Constant term')),
                ('discriminant', models.FloatField(help_text='Discriminant value')),
                ('root1', models.FloatField(blank=True, help_text='First root', null=True)),
                ('root2', models.FloatField(blank=True, help_text='Second root', null=True)),
                ('root1_imag', models.FloatField(default=0, help_text='Imaginary part of first root')),
                ('root2_imag', models.FloatField(default=0, help_text='Imaginary part of second root')),
                ('vertex_x', models.FloatField(help_text='X-coordinate of vertex')),
                ('vertex_y', models.FloatField(help_text='Y-coordinate of vertex')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quadratic Equation',
                'verbose_name_plural': 'Quadratic Equations',
                'ordering': ['-created_at'],
            },
        ),
    ]
